### PR TITLE
Add openapi-generator plugin in Gradle (instead of separated on CLI)

### PR DESCRIPTION
**Pull request by brainstorm**
Just a bit of gradle warnings cleanup and adding the OpenAPI generator in gradle as a task.

Related with issue https://github.com/ga4gh/drs-server/issues/1

/cc @victorskl @andrewpatto @reisingerf

### CODE REVIEW

**Comment by brainstorm** [comment]
@victorskl just pointed out that this (and upcoming changes) might better go to the `develop` branch instead of `master`... if so, could you set the preferred default branch?

**Comment by jb-adams** [comment]
thanks @brainstorm @victorskl you are correct, the default branch should have been `develop`. I've corrected it. Can you set this PR accordingly to close into `develop`? You will also have to rebase

I'm unfamiliar with what this plugin does, does it simply generate an OpenAPI document from the API controllers it detects?

**Comment by brainstorm** [comment]
> I'm unfamiliar with what this plugin does, does it simply generate an OpenAPI document from the API controllers it detects?

It generates code from the OpenAPI spec (.swagger.yaml file), not only docs, but actual boilerplate `.java` classes under `build` that you can reuse for your work. Give it a spin with `gradle openApiGenerate` and you'll see what I mean.

**Comment by brainstorm** [comment]
@jb-adams repointed to dev now ;)

**Comment by brainstorm** [comment]
Happy to close this @jb-adams if it doesn't make sense to you ;)

I just wanted to close the loop between OpenAPI yaml specs+codegen somehow so that they are in sync and (ref) implementations do not diverge from it.

**Comment by jb-adams** [comment]
thanks @brainstorm , yes maybe we'll close it. I'm not accustomed to codegen tools, though despite not using them we can expect 1:1 alignment between models defined here and the DRS spec, as someone on our tech team will always be maintaining it (and keeping up with Cloud WS-related spec updates).

we look forward to additional contributions from you once we get more up and running here

**Pull request closed without merging**
