### PR TITLE
Feature/51 migrate to gha

### PR DESCRIPTION
**Pull request by emre-f**
The tests that were run through GitHub actions passed. In the subsequent empty commit the caching was also successful.

Note: There was no docker integration step in the travis YAML file, so this workflow only has one job which is the unit test.

### CODE REVIEW

**Comment by emre-f** [comment]
I realized there is a separate issue for adding the docker integration. I will also add them here.

**Comment by emre-f** [comment]
Note: currently only the Unit-Test step is present. The Docker-Integration step will be added in a different PR (see Issue #52 )

**Review by jb-adams — CHANGES_REQUESTED** [review]
Looks good so far:

- Can you remove `.DS_Store` and `.github/.DS_Store` from source tracking, and add `.DS_Store` to `.gitignore`? These are macOS files
- Have you tested `DemoServerCorsTest`, `DemoServerCustomExceptionHandlingTest`, and `DemoServerMultiPortTest`? These seem to be lifted directly from the starter kit common testing library. The endpoints for that app are different than those for DRS, so I would expect all these tests to fail if you actually ran them. If this is the case, it's best to delete them, as they are testing functionality that is developed in `common`, so we do not need to re-test in `drs`
- have you manually tested the new Dockerfile to confirm that it builds successfully?

**Review by jb-adams — APPROVED** [review]

**Comment by emre-f** [comment]
- I have removed the DS_Store files, also added it into the .gitignore file.
- I have removed those test files, you are right they don't work. You will find the new and correct integration test files in the next PR (#58), in this one I am just migrating the Unit-Test.
- I tried manually building the Docker image and it worked. Furthermore, the docker integration tests pass in the next PR, which uses that Dockerfile to build the docker image for testing.

**Pull request merged**
